using Godot;

/// <summary>
/// The music: one track at a time, crossfaded when it changes. A child of <see cref="GameRoot"/>
/// so it carries on across screens - the menu track plays unbroken from the title through
/// fighter and stage select, and only a match changes it.
///
/// The tracks are generated by tools/audio/music.py and loop seamlessly by construction.
/// </summary>
public partial class MusicPlayer : Node
{
	public const string Menu = "menu";
	public const string Battle = "battle";

	public static MusicPlayer Instance { get; private set; }

	/// <summary>Where the music sits under the sound effects. Both tracks are mastered to the same
	/// peak, so this one number is the whole music-to-effects balance.</summary>
	const float VolumeDb = -9.0f;

	/// <summary>How far the music drops while the game is paused - still there, clearly waiting.</summary>
	const float PausedDb = -12.0f;

	const float FadeSeconds = 0.6f;

	AudioStreamPlayer current;
	AudioStreamPlayer fading;
	string currentName = "";
	float duckDb;

	public override void _Ready()
	{
		Instance = this;
		ProcessMode = ProcessModeEnum.Always;
		current = MakePlayer();
		fading = MakePlayer();
	}

	public override void _ExitTree()
	{
		if (Instance == this) Instance = null;
	}

	AudioStreamPlayer MakePlayer()
	{
		var player = new AudioStreamPlayer { Bus = SfxPlayer.MusicBus, VolumeDb = -80.0f };
		AddChild(player);
		return player;
	}

	/// <summary>Plays a track, crossfading from whatever was playing. Asking for the track that is
	/// already playing does nothing, so screens can ask freely.</summary>
	public static void Play(string name) => Instance?.Switch(name);

	/// <summary>Fades the music out.</summary>
	public static void Stop() => Instance?.Switch("");

	/// <summary>Turns the music down while paused, and back up after.</summary>
	public static void SetPaused(bool paused)
	{
		if (Instance != null) Instance.duckDb = paused ? PausedDb : 0.0f;
	}

	void Switch(string name)
	{
		if (name == currentName) return;
		currentName = name;

		(current, fading) = (fading, current);
		current.Stop();
		current.VolumeDb = -80.0f;
		if (name == "") return;

		AudioStream stream = SfxPlayer.Load($"res://assets/music/{name}.wav", loops: true);
		if (stream == null) return;
		current.Stream = stream;
		current.Play();
	}

	public override void _Process(double delta)
	{
		// Fades in decibels feel uneven - most of the change happens at the quiet end - so fade
		// the linear gain and convert.
		float step = (float)delta / FadeSeconds;
		float target = Mathf.DbToLinear(VolumeDb + duckDb);
		float now = Mathf.DbToLinear(current.VolumeDb);
		current.VolumeDb = Mathf.LinearToDb(Mathf.MoveToward(now, currentName == "" ? 0.0f : target, step * target));

		if (fading.Playing)
		{
			float old = Mathf.MoveToward(Mathf.DbToLinear(fading.VolumeDb), 0.0f, step * target);
			fading.VolumeDb = Mathf.LinearToDb(old);
			if (old <= 0.0001f) fading.Stop();
		}
	}
}
