using Godot;

/// <summary>
/// Every sound effect by name, and which one each move makes.
///
/// A move's sound is read off its data rather than authored per move: five fighters with
/// seventeen moves each would be eighty-five choices to keep in step with every rebalance, and
/// a new kid's fighter would arrive silent. Instead a sword swings like a sword, a smash swings
/// heavy, and a fireball roars, whoever throws it. A move that needs something the rules do not
/// give it can set <see cref="MoveData.Sound"/>.
///
/// The files are generated by tools/audio/ - see .ai/audio-direction.md.
/// </summary>
public static class SfxCatalog
{
	public static readonly string[] AllNames =
	{
		"swing_light", "swing_medium", "swing_heavy", "swing_blade", "smash_charge", "taunt",
		"special_shot", "special_volley", "special_fire", "special_beam", "special_dash", "special_glint",
		"special_blink", "special_rise", "special_wings", "special_hook", "special_trap",
		"special_drop", "special_resize", "special_quake", "special_build", "bomb_fuse", "explosion",
		"hit_light", "hit_medium", "hit_heavy", "hit_smash", "hit_block",
		"count_tick", "count_go", "ko_blast", "respawn", "game_set",
		"ui_move", "ui_select", "ui_back", "ui_ready", "pause",
		"zap", "jets", "missile", "steam", "overheat", "furnace_blast", "burn", "creak",
	};

	/// <summary>Sounds that loop until stopped. Everything else is a one-shot.</summary>
	public static bool Loops(string name) => name == "smash_charge";

	public static string PathFor(string name) => $"res://assets/sfx/{name}.wav";

	/// <summary>A sound and the move frame it plays on - 1 is the first frame of the move.</summary>
	public readonly struct Cue
	{
		public readonly string Name;
		public readonly int Frame;

		public Cue(string name, int frame)
		{
			Name = name;
			Frame = Mathf.Max(1, frame);
		}

		public bool IsNone => string.IsNullOrEmpty(Name);
	}

	/// <summary>
	/// How many frames a swing's whoosh starts before its hitbox comes out. The whoosh swells to
	/// its loudest about a third of the way through, so starting it early puts the rush of air
	/// on the hit rather than after it.
	/// </summary>
	const int SwingLeadFrames = 4;

	/// <summary>The sound a move makes and when. <paramref name="chargeFrame"/> is the frame a
	/// smash freezes on while held, so its swing waits for the release.</summary>
	public static Cue ForMove(MoveData move, int chargeFrame)
	{
		int active = move.StartupFrames + 1;

		if (!string.IsNullOrEmpty(move.Sound))
		{
			return new Cue(move.Sound, move.Special == SpecialKind.None ? active - SwingLeadFrames : active);
		}

		switch (move.Special)
		{
			case SpecialKind.Projectile when move.Beam:
				// The beam's own charge whine leads into the zap, so it starts with the move.
				return new Cue("special_beam", 1);
			case SpecialKind.Projectile when move.ShotAngles.Length > 0 || move.Mirrored || move.FromGround:
				// Summoned swords, a ring of daggers: many at once, not a single shot.
				return new Cue("special_volley", active);
			case SpecialKind.Projectile when move.FxFlame:
				return new Cue("special_fire", active);
			case SpecialKind.Projectile when move.FxMissile:
				return new Cue("missile", active);
			case SpecialKind.Projectile:
				return new Cue("special_shot", active);

			case SpecialKind.Dash when move.Blink:
				// The glint is 22 frames long and rises to a peak on the frame he goes. The sharp
				// cut that follows is played by the blink itself. See .ai/fighting-design.md.
				return new Cue("special_glint", active - 22);
			case SpecialKind.Dash:
				return new Cue("special_dash", 1);

			case SpecialKind.Recovery when move.ActiveFx == ActiveFx.Jets:
				// Lit halfway through the startup, when the flames first show.
				return new Cue("jets", move.StartupFrames / 2 + 1);
			case SpecialKind.Recovery when move.Flight:
				return new Cue("special_wings", 1);
			case SpecialKind.Recovery when move.DelayedLaunch:
				return new Cue("special_hook", active);
			case SpecialKind.Recovery:
				return new Cue("special_rise", 1);

			case SpecialKind.Trap: return new Cue("special_trap", active);
			case SpecialKind.Drop: return new Cue("special_drop", active);
			case SpecialKind.Resize: return new Cue("special_resize", active);
			case SpecialKind.Bomb: return new Cue("bomb_fuse", 1);
			case SpecialKind.Shockwave: return new Cue("special_quake", active);
			case SpecialKind.BuildPlatform: return new Cue("special_build", active);

			// Picking a sword starts the sword's own move, which makes its own sound.
			case SpecialKind.Choice: return default;

			// The arms shooting out: a thwip, and the clank of claws closing.
			case SpecialKind.CommandGrab: return new Cue("special_hook", 1);

			// Steam or flame depends on how hot he is when it goes, so the move plays it itself.
			case SpecialKind.Vent: return default;
		}

		// Electricity crackles when it is live, with no whoosh leading in - nothing is swung.
		if (move.ActiveFx == ActiveFx.Electric) return new Cue("zap", active);

		int swingFrame = move.Chargeable ? chargeFrame + 1 : active - SwingLeadFrames;
		return new Cue(SwingFor(move), swingFrame);
	}

	static string SwingFor(MoveData move)
	{
		if (IsBlade(move.HeldArt) || IsBlade(move.SwingArt) || IsBlade(move.PropArt)) return "swing_blade";
		if (move.Chargeable || move.Damage >= 13.0f) return "swing_heavy";
		if (move.Damage >= 8.0f) return "swing_medium";
		return "swing_light";
	}

	static bool IsBlade(string art)
	{
		if (string.IsNullOrEmpty(art)) return false;
		string a = art.ToLowerInvariant();
		// Not "edge": that is in sledgehammer.
		return a.Contains("sword") || a.Contains("blade") || a.Contains("katana")
			|| a.Contains("dagger") || a.Contains("claymore");
	}

	/// <summary>
	/// The hit sound, by knockback rather than damage: knockback is what the victim feels, and
	/// it is what the rumble and the camera shake already scale with. Around 150 is kill range.
	/// </summary>
	public static string ForHit(float knockback, bool blocked)
	{
		if (blocked) return "hit_block";
		if (knockback >= 125.0f) return "hit_smash";
		if (knockback >= 80.0f) return "hit_heavy";
		if (knockback >= 45.0f) return "hit_medium";
		return "hit_light";
	}
}
